In [1]:
import numpy as np
my_list = [1, 2, 3]
array_1d = np.array(my_list)
matrix_2d = [[1,2,3],[4,5,6],[7,8,9]]
array_2d = np.array(matrix_2d)



In [2]:
array_1d

array([1, 2, 3])

In [3]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.linspace(0, 5, 100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(5)

array([0.34964696, 0.94854943, 0.2196913 , 0.91742284, 0.54733143])

In [18]:
np.random.rand(5, 5)

array([[0.19648909, 0.90657195, 0.19139638, 0.99517371, 0.63125211],
       [0.96175398, 0.92642696, 0.41865216, 0.51623045, 0.75196293],
       [0.71053407, 0.30659514, 0.79045984, 0.19392195, 0.37700656],
       [0.35946046, 0.69039344, 0.7617572 , 0.7148349 , 0.8536835 ],
       [0.34880093, 0.08870948, 0.49829552, 0.51746729, 0.08345438]])

In [19]:
np.random.randn(2)

array([ 0.52200719, -0.9993344 ])

In [20]:
np.random.randn(4, 4)

array([[-1.12309755, -0.15559902,  0.72077472,  0.04319472],
       [-1.01984719,  0.01241076, -0.81317003,  0.16454332],
       [ 0.63174122,  0.10583461,  1.92262074,  0.77312263],
       [ 0.13152537, -0.63262833, -0.26165748, -1.14720408]])

In [21]:
np.random.randint(1, 100)

30

In [22]:
np.random.randint(1, 100, 10)

array([50,  3, 79, 72, 28, 82, 24, 58, 49, 65], dtype=int32)

In [29]:
arr = np.arange(25)
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr.shape

(25,)

In [39]:
arr.dtype

dtype('int64')

In [31]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([32, 36, 40, 24, 41, 14, 26, 36, 38, 46], dtype=int32)

In [34]:
ranarr.max()

np.int32(46)

In [35]:
ranarr.min()

np.int32(14)

In [36]:
ranarr.argmax()

np.int64(9)

In [37]:
ranarr.argmin()

np.int64(5)