In [15]:
import numpy as np
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr[8]


np.int64(8)

In [17]:
arr[1:5]

array([1, 2, 3, 4])

In [18]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [19]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [20]:
arr[:5] = 100

In [21]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [22]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
slice_of_arr = arr[:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [24]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr_copy = arr.copy()

In [28]:
arr_copy[:] = 100

In [29]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [30]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [37]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [38]:
arr_2d[2,1]

np.int64(40)

In [39]:
arr_2d[1,2]

np.int64(30)

In [40]:
## How slicing works in 2D:
#arr_2d[row_slice , column_slice]

#Meaning of the slice

#:2 → take rows from start up to row index 2 (not including 2).

#1: → take columns from index 1 to the end.

arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [42]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
bool_arr = arr > 5

In [44]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [45]:
arr[arr < 3]

array([1, 2])